import { NextResponse } from 'next/server'

const tokens = {
  $schema: 'https://felix-design.vercel.app/json',
  name: 'Félix Design System',
  version: '1.0.0',

  color: {
    brand: {
      turquoise: { value: '#2BF2F1', description: 'Primary brand color' },
      slate: { value: '#082422', description: 'Secondary brand color' },
    },
    neutral: {
      concrete: { value: '#CFCABF', description: 'Warm gray neutral' },
      stone: { value: '#EFEBE7', description: 'Light warm neutral' },
      linen: { value: '#FEFCF9', description: 'Off-white background' },
    },
    secondary: {
      blueberry: { value: '#6060BF', description: 'Secondary accent' },
      evergreen: { value: '#35605F', description: 'Dark green accent' },
      mocha: { value: '#877867', description: 'Brown accent' },
      papaya: { value: '#F26629', description: 'Orange/error accent' },
      sky: { value: '#8DFDFA', description: 'Light cyan accent' },
      cactus: { value: '#60D06F', description: 'Green/success accent' },
      yam: { value: '#C1A98A', description: 'Tan accent' },
      mango: { value: '#F19D38', description: 'Orange accent' },
      'light-sky': { value: '#D4FFFE', description: 'Very light cyan' },
      lime: { value: '#DCFF00', description: 'Yellow-green accent' },
      lychee: { value: '#FFCD9C', description: 'Peach accent' },
      fortuna: { value: '#FFB05A', description: 'Light orange accent' },
      sage: { value: '#7BA882', description: 'Muted green accent' },
    },
    scale: {
      turquoise: {
        50: '#F0FFFE',
        100: '#D4FFFE',
        200: '#8DFDFA',
        300: '#5AF7F5',
        400: '#2BF2F1',
        500: '#20D5D4',
        600: '#17ADAC',
        700: '#0F8584',
        800: '#0A5E5D',
        900: '#063D3C',
        950: '#032221',
      },
      slate: {
        50: '#F0F5F4',
        100: '#D4E0DF',
        200: '#A8C1BF',
        300: '#7DA29F',
        400: '#51837F',
        500: '#35605F',
        600: '#2A4D4C',
        700: '#1F3A39',
        800: '#152726',
        900: '#082422',
        950: '#041211',
      },
    },
    semantic: {
      light: {
        background: { value: '#FEFCF9', token: '--background' },
        foreground: { value: '#082422', token: '--foreground' },
        card: { value: '#EFEBE7', token: '--card' },
        'card-foreground': { value: '#082422', token: '--card-foreground' },
        primary: { value: '#2BF2F1', token: '--primary' },
        'primary-foreground': { value: '#082422', token: '--primary-foreground' },
        secondary: { value: '#CFCABF', token: '--secondary' },
        'secondary-foreground': { value: '#082422', token: '--secondary-foreground' },
        muted: { value: '#EFEBE7', token: '--muted' },
        'muted-foreground': { value: '#35605F', token: '--muted-foreground' },
        accent: { value: '#2BF2F1', token: '--accent' },
        'accent-foreground': { value: '#082422', token: '--accent-foreground' },
        destructive: { value: '#F26629', token: '--destructive' },
        border: { value: '#CFCABF', token: '--border' },
        input: { value: '#877867', token: '--input' },
        ring: { value: '#877867', token: '--ring' },
      },
      dark: {
        background: { value: '#082422', token: '--background' },
        foreground: { value: '#FEFCF9', token: '--foreground' },
        card: { value: '#082422', token: '--card' },
        'card-foreground': { value: '#FEFCF9', token: '--card-foreground' },
        primary: { value: '#2BF2F1', token: '--primary' },
        'primary-foreground': { value: '#082422', token: '--primary-foreground' },
        secondary: { value: '#35605F', token: '--secondary' },
        'secondary-foreground': { value: '#FEFCF9', token: '--secondary-foreground' },
        muted: { value: '#35605F', token: '--muted' },
        'muted-foreground': { value: '#CFCABF', token: '--muted-foreground' },
        accent: { value: '#2BF2F1', token: '--accent' },
        'accent-foreground': { value: '#082422', token: '--accent-foreground' },
        destructive: { value: '#F26629', token: '--destructive' },
        border: { value: '#35605F', token: '--border' },
        input: { value: '#35605F', token: '--input' },
        ring: { value: '#CFCABF', token: '--ring' },
      },
    },
    chart: {
      1: { value: '#2BF2F1', name: 'Turquoise' },
      2: { value: '#6060BF', name: 'Blueberry' },
      3: { value: '#60D06F', name: 'Cactus' },
      4: { value: '#F19D38', name: 'Mango' },
      5: { value: '#F26629', name: 'Papaya' },
    },
    sidebar: {
      background: { value: '#082422' },
      foreground: { value: '#FEFCF9' },
      primary: { value: '#2BF2F1' },
      'primary-foreground': { value: '#082422' },
      accent: { value: '#35605F' },
      'accent-foreground': { value: '#FEFCF9' },
      border: { value: '#35605F' },
      ring: { value: '#2BF2F1' },
    },
  },

  spacing: {
    xs: { value: '0.25rem', px: 4, description: 'Tight gaps, icon spacing', tailwind: 'gap-1, p-1' },
    sm: { value: '0.5rem', px: 8, description: 'Related elements, small padding', tailwind: 'gap-2, p-2' },
    md: { value: '1rem', px: 16, description: 'Standard component padding', tailwind: 'gap-4, p-4' },
    lg: { value: '1.5rem', px: 24, description: 'Section gaps, card padding', tailwind: 'gap-6, p-6' },
    xl: { value: '2rem', px: 32, description: 'Large section spacing', tailwind: 'gap-8, p-8' },
    '2xl': { value: '3rem', px: 48, description: 'Major section separators', tailwind: 'gap-12, py-12' },
    '3xl': { value: '4rem', px: 64, description: 'Page-level spacing', tailwind: 'gap-16, py-16' },
  },

  borderRadius: {
    none: { value: '0px', tailwind: 'rounded-none' },
    sm: { value: '0.25rem', px: 4, tailwind: 'rounded-sm' },
    md: { value: '0.5rem', px: 8, tailwind: 'rounded-md' },
    lg: { value: '1rem', px: 16, tailwind: 'rounded-lg' },
    xl: { value: '1.5rem', px: 24, tailwind: 'rounded-xl' },
    '2xl': { value: '2rem', px: 32, tailwind: 'rounded-2xl' },
    full: { value: '9999px', tailwind: 'rounded-full' },
  },

  shadow: {
    xs: { value: '0 1px 2px rgba(8, 36, 34, 0.03)', description: 'Subtle depth for inputs', tailwind: 'shadow-xs' },
    sm: { value: '0 1px 3px rgba(8, 36, 34, 0.06), 0 1px 2px rgba(8, 36, 34, 0.04)', description: 'Buttons, form controls', tailwind: 'shadow-sm' },
    md: { value: '0 4px 6px rgba(8, 36, 34, 0.06), 0 2px 4px rgba(8, 36, 34, 0.04)', description: 'Cards, dropdowns', tailwind: 'shadow-md' },
    lg: { value: '0 10px 15px rgba(8, 36, 34, 0.06), 0 4px 6px rgba(8, 36, 34, 0.03)', description: 'Popovers, tooltips', tailwind: 'shadow-lg' },
    xl: { value: '0 20px 25px rgba(8, 36, 34, 0.06), 0 8px 10px rgba(8, 36, 34, 0.03)', description: 'Modals, dialogs', tailwind: 'shadow-xl' },
    '2xl': { value: '0 25px 50px rgba(8, 36, 34, 0.12)', description: 'High-emphasis elements', tailwind: 'shadow-2xl' },
    inner: { value: 'inset 0 2px 4px rgba(8, 36, 34, 0.04)', description: 'Pressed states', tailwind: 'shadow-inner' },
    turquoise: { value: '0 4px 14px rgba(43, 242, 241, 0.25)', description: 'Brand accent glow', tailwind: 'shadow-turquoise' },
  },

  typography: {
    fontFamily: {
      display: { value: 'Geist, sans-serif', description: 'Headlines, titles, display text' },
      body: { value: 'Geist, sans-serif', description: 'Body text, paragraphs, UI elements' },
    },
    fontSize: {
      caption: { value: '0.75rem', px: 12, tailwind: 'text-xs' },
      'body-sm': { value: '0.875rem', px: 14, tailwind: 'text-sm' },
      body: { value: '1rem', px: 16, tailwind: 'text-base' },
      'body-lg': { value: '1.125rem', px: 18, tailwind: 'text-lg' },
      'heading-4': { value: '1.25rem', px: 20, tailwind: 'text-xl' },
      'heading-3': { value: '1.5rem', px: 24, tailwind: 'text-2xl' },
      'heading-2': { value: '1.875rem', px: 30, tailwind: 'text-3xl' },
      'heading-1': { value: '2.25rem', px: 36, tailwind: 'text-4xl' },
      'display-md': { value: '3rem', px: 48, tailwind: 'text-5xl' },
      'display-lg': { value: '3.75rem', px: 60, tailwind: 'text-6xl' },
      'display-xl': { value: '4.5rem', px: 72, tailwind: 'text-7xl' },
    },
    lineHeight: {
      none: { value: '1', description: 'Display text' },
      display: { value: '1.1', description: 'Display MD' },
      'heading-1': { value: '1.2', description: 'Heading 1' },
      'heading-2': { value: '1.3', description: 'Heading 2' },
      'heading-3': { value: '1.4', description: 'Heading 3, Caption' },
      'heading-4': { value: '1.5', description: 'Heading 4, Body Small' },
      body: { value: '1.6', description: 'Body, Body Large' },
    },
    letterSpacing: {
      display: { value: '-0.02em', description: 'Display text', tailwind: 'tracking-tight' },
      heading: { value: '-0.01em', description: 'Headings', tailwind: 'tracking-tight' },
      normal: { value: '0em', description: 'Body text', tailwind: 'tracking-normal' },
      caption: { value: '0.01em', description: 'Caption, uppercase', tailwind: 'tracking-wide' },
    },
    fontWeight: {
      light: { value: 300, tailwind: 'font-light' },
      normal: { value: 400, tailwind: 'font-normal' },
      medium: { value: 500, tailwind: 'font-medium' },
      semibold: { value: 600, tailwind: 'font-semibold' },
      bold: { value: 700, tailwind: 'font-bold' },
      extrabold: { value: 800, tailwind: 'font-extrabold' },
    },
  },
}

export async function GET() {
  return new NextResponse(JSON.stringify(tokens, null, 2), {
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      'Cache-Control': 'public, max-age=3600, s-maxage=86400',
      'Access-Control-Allow-Origin': '*',
    },
  })
}
