/**
 * One-time script: copy the /preso-sample deck into kyle.cooney@felixpago.com's studio account.
 *
 * Run: source <(grep -v '^#' .env.local | sed 's/^/export /') && npx tsx scripts/copy-preso-sample.ts
 */

import { getUserByEmail, createPresentation } from '../lib/studio-db'

const slides: any[] = [
  {
    type: 'two-column',
    bg: 'light',
    badge: 'North Star',
    title: 'Félix North Star',
    columns: [
      {
        heading: '',
        body: 'Become the companion for Latinos in the United States enabling them to access financial services throughout their journey as immigrants.',
      },
      {
        heading: 'Mission',
        body: 'To empower Latinos in the US to care for what matters most back home.',
        bullets: [
          { text: 'We are obsessed about our customers', icon: '✓' },
          { text: 'We get sh*t done with urgency and focus', icon: '✓' },
          { text: 'We collaborate without ego', icon: '✓' },
          { text: 'We practice extreme ownership', icon: '✓' },
          { text: 'We aim for insanely great', icon: '✓' },
          { text: 'We are insatiably curious', icon: '✓' },
        ],
      },
    ],
    imageUrl: '/illustrations/F%C3%A9lix%20Illo%201.svg',
    notes: 'Two-column layout with Félix mascot illustration and a Mission + Key Principles card. Light stone background with floating money illustrations (Flying Dollar Bills, Cloud Coin, Dollar bills + Coins).',
  },
  {
    type: 'cards',
    bg: 'light',
    title: 'Our Values',
    cards: [
      { title: '01 — User-Obsession', titleColor: '#082422', body: 'We have to earn the right to serve our users every day and never take it for granted. We always remember the hard work our users went through to send this money. We are always here for them.' },
      { title: '02 — Getting Sh*t Done With Urgency', titleColor: '#2BF2F1', body: 'We have a bias towards action. Champions adjust! We care less about what others are doing and focus on what we want to accomplish.' },
      { title: '03 — Extreme Ownership', titleColor: '#35605F', body: 'Each person in the company owns a mission-critical piece of the vision. No weak links. No passengers.' },
      { title: '04 — No-Ego Collab', titleColor: '#877867', body: 'We disagree clearly, and we commit once a decision is made. We break silos, we move in lockstep. We are a team, not a group of individuals.' },
      { title: '05 — Aim For Insanely Great', titleColor: '#2BF2F1', body: 'We elevate the quality of our output by caring deeply. We obsess about every customer moment.' },
      { title: '06 — Insatiable Curiosity', titleColor: '#082422', body: 'We listen closely to our users and base our assumptions in data. We test assumptions and never take anything for granted. We experiment relentlessly.' },
    ],
    notes: 'Six value cards displayed as a fanned card deck with hover interaction. Each card has a large number, illustration, title, and description. Alternating dark/turquoise/evergreen/stone backgrounds.',
  },
  {
    type: 'cards',
    bg: 'dark',
    title: 'Rules of the Land',
    cards: [
      { title: '1. Share What Matters', titleColor: '#2BF2F1', body: "Lead with metrics, impact, and insights tied to quarterly goals. Ask yourself: Does this show impact? Does it connect to what we're building?" },
      { title: '2. Be Concise', titleColor: '#6060BF', body: "State your time upfront — we'll hold you to it. Cap slide decks at 4 slides max. If it can be a one-liner, make it a one-liner." },
      { title: '3. Limit Demos', titleColor: '#60D06F', body: 'Keep demos under 2 minutes. Have links ready so anyone can dig deeper async.' },
      { title: '4. Follow the Structure', titleColor: '#F19D38', body: 'Objective — Goal of the initiative. Action — What was done. Impact — Results or learnings. Next Steps — If applicable.' },
    ],
    notes: 'Four colorful rule cards in a 2x2 grid. Card 1 turquoise bg, Card 2 blueberry bg, Card 3 cactus bg, Card 4 mango bg. Each has a large background number and decorative illustration.',
  },
  {
    type: 'bullets',
    bg: 'light',
    badge: 'Agenda',
    title: 'Feb. 23rd — Feb. 27th',
    subtitle: "Today's Topics",
    bullets: [
      { text: 'Icebreaker — 3 min', icon: '1️⃣' },
      { text: 'FélixBook — 10 min', icon: '2️⃣' },
      { text: 'Weekly Recap — 5 min', icon: '3️⃣' },
      { text: 'Félix Weekly Updates — 35-40 min', icon: '4️⃣' },
    ],
    imageUrl: '/illustrations/Paper%20Airplane%20%2B%20Coin%20-%20Turquoise.svg',
    notes: 'Agenda slide with four items and time durations. Decorative paper airplane illustration in background. Light background.',
  },
  {
    type: 'cards',
    bg: 'light',
    badge: 'OKRs',
    title: 'Zoo Goals for Q1 2025',
    subtitle: 'What We\'re Targeting',
    cards: [
      { title: 'Reduce chaos caused by the geese', titleColor: '#2BF2F1', body: '• Zero goose-related HR incidents (currently 14) — At Risk 12%\n• 85% of visitors not chased by a goose — In Progress 63%\n• Successfully relocate Gerald the alpha goose — At Risk 0%' },
      { title: 'Convince the capybaras to do literally anything', titleColor: '#60D06F', body: '• At least 1 capybara visibly awake during zoo hours — On Track 47%' },
      { title: 'Urgent Animal Situations', titleColor: '#082422', body: '• Find out who taught the parrot to say "you\'re fired" — Not Started\n• Stop the raccoons from unionizing — In Progress' },
    ],
    notes: 'OKR goals slide with three objective groups, each with colored accent bars. Key results show status pills (On Track, In Progress, At Risk, Not Started) and horizontal progress bars.',
  },
  {
    type: 'two-column',
    bg: 'dark',
    badge: 'Product Demo',
    title: 'Send Money in 60 Seconds',
    columns: [
      {
        heading: 'Live Walkthrough',
        body: 'Our remittance flow is designed for speed and trust. Three screens, one tap to confirm, real-time delivery tracking.',
        bullets: [
          { text: '**Corridor Selection** — Auto-detected based on user profile and recent sends. One tap to confirm or change.', icon: '1️⃣' },
          { text: '**Amount & FX Lock** — Live exchange rate with 30-second lock. Recipient sees exact payout in local currency.', icon: '2️⃣' },
          { text: '**Review & Confirm** — Single-screen summary with biometric confirmation. No hidden fees, no surprises.', icon: '3️⃣' },
        ],
      },
      {
        heading: '',
        body: 'Embedded mobile device frame showing the Félix send flow demo.',
      },
    ],
    notes: 'Dark slide with product demo. Left side has editorial content with three numbered steps. Right side embeds a live mobile device frame with an iframe of the fintech test flow.',
  },
  {
    type: 'cards',
    bg: 'dark',
    badge: 'Leadership',
    title: 'Our Team',
    cards: [
      { title: 'Manuel Godoy — CEO', titleColor: '#2BF2F1', body: 'Reports: Carlos Reyes (CTO), Sofia Delgado (CFO), Valentina Cruz (CPO), Ricardo Mora (COO)' },
      { title: 'Carlos Reyes — CTO', titleColor: '#6060BF', body: 'Reports: Lucia Herrera (VP Engineering), Diego Solano (VP Data)' },
      { title: 'Sofia Delgado — CFO', titleColor: '#F19D38', body: 'Reports: Mateo Rios (Dir. Finance)' },
      { title: 'Valentina Cruz — CPO', titleColor: '#F26629', body: 'Reports: Andres Pena (Dir. Product), Camila Torres (Dir. Design)' },
      { title: 'Ricardo Mora — COO', titleColor: '#35605F', body: 'Reports: Isabel Vargas (Dir. Ops)' },
    ],
    notes: 'Org chart slide on dark background. CEO at top center with avatar, connected by lines to four C-suite executives below, each with their own director-level reports.',
  },
  {
    type: 'chart',
    bg: 'light',
    badge: 'Bar Chart',
    title: 'Transaction Volume by Corridor',
    body: 'Mexico leads all corridors with 4.2K weekly sends, accounting for 34% of total weekly volume.',
    chart: {
      chartType: 'bar',
      data: [
        { country: 'Mexico', volume: 4200 },
        { country: 'Guatemala', volume: 2800 },
        { country: 'El Salvador', volume: 1900 },
        { country: 'Honduras', volume: 1600 },
        { country: 'Colombia', volume: 1200 },
        { country: 'Nicaragua', volume: 800 },
        { country: 'Dom. Rep.', volume: 600 },
      ],
      xKey: 'country',
      yKeys: ['volume'],
      colors: ['#2BF2F1', '#60D06F', '#6060BF', '#F19D38', '#F26629', '#7BA882', '#FFCD9C'],
    },
    notes: 'Vertical bar chart showing weekly transaction volume by corridor. Each bar has a unique color. 12.3K weekly transactions total.',
  },
  {
    type: 'chart',
    bg: 'dark',
    badge: 'Stacked Bar',
    title: 'Revenue Growth by Product',
    body: 'Every product line grew, but credit building tripled its share. Remittances still anchors 64% of total revenue.',
    chart: {
      chartType: 'stacked-bar',
      data: [
        { quarter: 'Q1', remit: 2800, credit: 400, billpay: 300, savings: 150 },
        { quarter: 'Q2', remit: 3200, credit: 600, billpay: 450, savings: 200 },
        { quarter: 'Q3', remit: 3600, credit: 900, billpay: 550, savings: 320 },
        { quarter: 'Q4', remit: 4100, credit: 1200, billpay: 700, savings: 420 },
      ],
      xKey: 'quarter',
      yKeys: ['remit', 'credit', 'billpay', 'savings'],
      colors: ['#2BF2F1', '#6060BF', '#F19D38', '#60D06F'],
    },
    notes: 'Stacked bar chart showing revenue growth by product line across Q1-Q4. $6.4M Q4 total.',
  },
  {
    type: 'chart',
    bg: 'light',
    badge: 'Horizontal Bar',
    title: 'NPS by Corridor',
    body: 'Mexico leads satisfaction — Nicaragua shows the most room for improvement. Top 3 corridors all exceed industry benchmark of 70.',
    chart: {
      chartType: 'horizontal-bar',
      data: [
        { corridor: 'Mexico', nps: 82 },
        { corridor: 'Guatemala', nps: 74 },
        { corridor: 'El Salvador', nps: 71 },
        { corridor: 'Colombia', nps: 68 },
        { corridor: 'Honduras', nps: 65 },
        { corridor: 'Dom. Rep.', nps: 61 },
        { corridor: 'Nicaragua', nps: 58 },
      ],
      xKey: 'corridor',
      yKeys: ['nps'],
      colors: ['#2BF2F1'],
    },
    notes: 'Horizontal bar chart ranking NPS scores by corridor. Mexico highest at 82, Nicaragua lowest at 58.',
  },
  {
    type: 'chart',
    bg: 'dark',
    badge: 'Line Chart',
    title: 'Monthly Active Users',
    body: 'Félix MAU grew 271% in 8 months across all corridors. Organic growth drives 62% of new sign-ups.',
    chart: {
      chartType: 'line',
      data: [
        { month: 'Jul', users: 42 },
        { month: 'Aug', users: 58 },
        { month: 'Sep', users: 71 },
        { month: 'Oct', users: 89 },
        { month: 'Nov', users: 104 },
        { month: 'Dec', users: 118 },
        { month: 'Jan', users: 137 },
        { month: 'Feb', users: 156 },
      ],
      xKey: 'month',
      yKeys: ['users'],
      colors: ['#2BF2F1'],
    },
    notes: 'Area/line chart showing MAU growth from 42K in July to 156K in February. Turquoise gradient fill under the line.',
  },
  {
    type: 'chart',
    bg: 'light',
    badge: 'Multi-Line',
    title: 'Corridor Growth Trajectories',
    body: 'Mexico leads volume, but Colombia shows the steepest growth trajectory at 375% YTD.',
    chart: {
      chartType: 'multi-line',
      data: [
        { month: 'Jan', mx: 42, gt: 18, co: 8, sv: 12 },
        { month: 'Feb', mx: 48, gt: 20, co: 11, sv: 14 },
        { month: 'Mar', mx: 55, gt: 22, co: 15, sv: 13 },
        { month: 'Apr', mx: 63, gt: 19, co: 19, sv: 16 },
        { month: 'May', mx: 71, gt: 25, co: 24, sv: 18 },
        { month: 'Jun', mx: 78, gt: 28, co: 28, sv: 20 },
        { month: 'Jul', mx: 84, gt: 31, co: 33, sv: 22 },
        { month: 'Aug', mx: 92, gt: 34, co: 38, sv: 25 },
      ],
      xKey: 'month',
      yKeys: ['mx', 'gt', 'co', 'sv'],
      colors: ['#2BF2F1', '#6060BF', '#F19D38', '#60D06F'],
    },
    notes: 'Multi-line chart comparing corridor growth from Jan to Aug. Four lines for Mexico, Guatemala, Colombia, El Salvador.',
  },
  {
    type: 'chart',
    bg: 'dark',
    badge: 'Donut Chart',
    title: 'Revenue by Product',
    body: 'Remittances remain the core revenue driver at 62%. Credit building launched Q3, already 18% of revenue.',
    chart: {
      chartType: 'donut',
      data: [
        { name: 'Remittances', value: 62 },
        { name: 'Credit', value: 18 },
        { name: 'Bill Pay', value: 12 },
        { name: 'Savings', value: 8 },
      ],
      xKey: 'name',
      yKeys: ['value'],
      colors: ['#2BF2F1', '#6060BF', '#F19D38', '#60D06F'],
    },
    notes: 'Donut chart showing revenue split. Center displays 62% Remittances. $4.2M monthly revenue.',
  },
  {
    type: 'chart',
    bg: 'light',
    badge: 'Scatter Plot',
    title: 'Send Amount vs Frequency',
    body: 'High-frequency senders cluster around $200-400 amounts. Power senders average 8+ transactions per month.',
    chart: {
      chartType: 'scatter',
      data: [
        { amount: 150, frequency: 12 },
        { amount: 300, frequency: 22 },
        { amount: 500, frequency: 8 },
        { amount: 200, frequency: 18 },
        { amount: 400, frequency: 15 },
        { amount: 750, frequency: 4 },
        { amount: 100, frequency: 25 },
        { amount: 350, frequency: 20 },
      ],
      xKey: 'amount',
      yKeys: ['frequency'],
      colors: ['#2BF2F1', '#F19D38', '#6060BF'],
    },
    notes: 'Scatter plot showing correlation between send amount and frequency. r=0.72 correlation.',
  },
  {
    type: 'chart',
    bg: 'dark',
    badge: 'Histogram',
    title: 'Transaction Amount Distribution',
    body: 'The $101-200 bucket has the highest volume — our sweet spot. 80% of all sends fall between $50 and $500.',
    chart: {
      chartType: 'bar',
      data: [
        { range: '$0-50', count: 180 },
        { range: '$51-100', count: 420 },
        { range: '$101-200', count: 680 },
        { range: '$201-300', count: 520 },
        { range: '$301-500', count: 340 },
        { range: '$501-750', count: 190 },
        { range: '$751-1K', count: 90 },
        { range: '$1K+', count: 40 },
      ],
      xKey: 'range',
      yKeys: ['count'],
      colors: ['#7BA882', '#60D06F', '#2BF2F1', '#6060BF', '#F19D38', '#F26629', '#35605F', '#FFCD9C'],
    },
    notes: 'Histogram showing transaction amount distribution across 8 buckets. $101-200 is the peak. $201 median send.',
  },
  {
    type: 'chart',
    bg: 'light',
    badge: 'Heat Map',
    title: 'Send Activity by Day & Time',
    body: 'Friday noon is the busiest period — payday sending. Weekend activity skews toward evening hours.',
    chart: {
      chartType: 'bar',
      data: [
        { day: 'Mon', peak: 8 },
        { day: 'Tue', peak: 12 },
        { day: 'Wed', peak: 10 },
        { day: 'Thu', peak: 14 },
        { day: 'Fri', peak: 15 },
        { day: 'Sat', peak: 10 },
        { day: 'Sun', peak: 8 },
      ],
      xKey: 'day',
      yKeys: ['peak'],
      colors: ['#2BF2F1'],
    },
    notes: 'Heat map showing send activity by day of week and time of day. 7 rows × 9 columns. Friday 10am-12pm is the peak window. Original uses color intensity grid.',
  },
  {
    type: 'chart',
    bg: 'dark',
    badge: 'Treemap',
    title: 'Market Share by Region',
    body: 'Mexico alone represents 42% of total market share. Caribbean expansion added 18% new volume this year.',
    chart: {
      chartType: 'bar',
      data: [
        { name: 'Mexico', size: 42 },
        { name: 'Guatemala', size: 12 },
        { name: 'Dom. Rep.', size: 10 },
        { name: 'Colombia', size: 9 },
        { name: 'El Salvador', size: 8 },
        { name: 'Caribbean Other', size: 8 },
        { name: 'Honduras', size: 6 },
        { name: 'S. America Other', size: 5 },
      ],
      xKey: 'name',
      yKeys: ['size'],
      colors: ['#2BF2F1', '#60D06F', '#6060BF', '#7BA882', '#F19D38', '#FFCD9C', '#F26629', '#35605F'],
    },
    notes: 'Treemap showing market share by region. Mexico is the largest tile at 42%. 68% LATAM share. Original renders as nested rectangles.',
  },
  {
    type: 'chart',
    bg: 'light',
    badge: 'Sankey / Funnel',
    title: 'User Send Flow',
    body: 'The biggest drop-off happens at corridor selection — 18% leave. Users who complete first send have 82% retention.',
    chart: {
      chartType: 'horizontal-bar',
      data: [
        { stage: 'App Open', value: 100 },
        { stage: 'Select Corridor', value: 82 },
        { stage: 'Enter Amount', value: 71 },
        { stage: 'Review', value: 64 },
        { stage: 'Confirmed', value: 64 },
      ],
      xKey: 'stage',
      yKeys: ['value'],
      colors: ['#2BF2F1'],
    },
    notes: 'Sankey-style flow diagram showing user progression from App Open (100%) to Confirmed (64%). 64% completion rate.',
  },
  {
    type: 'chart',
    bg: 'dark',
    badge: 'Waterfall',
    title: 'Revenue Bridge',
    body: 'From $4.2M revenue to $1.0M net income. COGS reduced 8% through partner negotiations.',
    chart: {
      chartType: 'bar',
      data: [
        { name: 'Revenue', value: 4200 },
        { name: 'COGS', value: -1200 },
        { name: 'Gross Profit', value: 3000 },
        { name: 'OpEx', value: -800 },
        { name: 'Marketing', value: -400 },
        { name: 'Net Income', value: 1000 },
      ],
      xKey: 'name',
      yKeys: ['value'],
      colors: ['#60D06F', '#F26629', '#2BF2F1', '#F26629', '#F26629', '#2BF2F1'],
    },
    notes: 'Waterfall chart showing revenue bridge. Green/turquoise for positive values, papaya for deductions. $1.0M net income.',
  },
  {
    type: 'chart',
    bg: 'light',
    badge: 'Box Plot',
    title: 'Transfer Time by Corridor',
    body: 'Mexico has the fastest, most consistent delivery times. 95% of Mexico transfers under 30 minutes.',
    chart: {
      chartType: 'bar',
      data: [
        { corridor: 'MX', median: 15 },
        { corridor: 'GT', median: 30 },
        { corridor: 'SV', median: 22 },
        { corridor: 'HN', median: 35 },
        { corridor: 'CO', median: 25 },
      ],
      xKey: 'corridor',
      yKeys: ['median'],
      colors: ['#2BF2F1', '#60D06F', '#6060BF', '#F19D38', '#7BA882'],
    },
    notes: 'Box plot with whiskers, quartile boxes, and median lines for 5 corridors. Mexico median 15 min. Original renders as custom SVG box plots.',
  },
  {
    type: 'chart',
    bg: 'dark',
    badge: 'Bubble Chart',
    title: 'Market Opportunity Matrix',
    body: 'X = volume, Y = satisfaction, size = market potential. Mexico TAM alone exceeds $4B annually.',
    chart: {
      chartType: 'scatter',
      data: [
        { amount: 4200, frequency: 87, name: 'MX' },
        { amount: 2800, frequency: 64, name: 'GT' },
        { amount: 1900, frequency: 52, name: 'SV' },
        { amount: 1600, frequency: 45, name: 'HN' },
        { amount: 1200, frequency: 38, name: 'CO' },
        { amount: 800, frequency: 24, name: 'NI' },
      ],
      xKey: 'amount',
      yKeys: ['frequency'],
      colors: ['#2BF2F1', '#60D06F', '#6060BF', '#F19D38', '#7BA882', '#F26629'],
    },
    notes: 'Bubble scatter chart. X-axis is volume, Y-axis is CSAT, bubble size is market potential (TAM). $12B total addressable.',
  },
  {
    type: 'chart',
    bg: 'light',
    badge: 'Radar Chart',
    title: 'Product Comparison',
    body: 'Remittances leads across most metrics — credit building has the most room to grow.',
    chart: {
      chartType: 'radar',
      data: [
        { metric: 'Speed', remit: 92, credit: 68, savings: 75 },
        { metric: 'Trust', remit: 88, credit: 85, savings: 82 },
        { metric: 'Simplicity', remit: 90, credit: 62, savings: 78 },
        { metric: 'Adoption', remit: 95, credit: 45, savings: 55 },
        { metric: 'Retention', remit: 82, credit: 78, savings: 70 },
        { metric: 'NPS', remit: 87, credit: 72, savings: 68 },
      ],
      xKey: 'metric',
      yKeys: ['remit', 'credit', 'savings'],
      colors: ['#2BF2F1', '#6060BF', '#60D06F'],
    },
    notes: 'Radar chart comparing three products across 6 metrics. Remittances fills the largest area.',
  },
  {
    type: 'cards',
    bg: 'dark',
    badge: 'Gantt Chart',
    title: 'Product Roadmap',
    subtitle: 'Q2-Q4 2026',
    cards: [
      { title: 'DS Tokens V2', titleColor: '#2BF2F1', body: 'Month 1-3 · Foundation layer unblocking all downstream design work' },
      { title: 'Component Library', titleColor: '#6060BF', body: 'Month 2-6 · Full rebuild of shared component library' },
      { title: 'Credit Flow', titleColor: '#60D06F', body: 'Month 3-6 · New credit building product flow' },
      { title: 'Bill Pay MVP', titleColor: '#F19D38', body: 'Month 5-7 · Minimum viable bill pay experience' },
      { title: 'Savings Launch', titleColor: '#7BA882', body: 'Month 6-9 · Digital savings product launch' },
      { title: 'Multi-currency', titleColor: '#F26629', body: 'Month 7-9 · Three new corridor currencies' },
      { title: 'Illo Library V2', titleColor: '#FFCD9C', body: 'Month 4-5 · Illustration library refresh' },
    ],
    notes: 'Gantt chart showing product roadmap Q2-Q4 2026. Seven parallel workstreams. Original renders as horizontal timeline bars.',
  },
  {
    type: 'chart',
    bg: 'light',
    badge: 'Funnel Chart',
    title: 'User Conversion Funnel',
    body: 'KYC is the biggest cliff — investing in smoother verification could unlock 18% more users.',
    chart: {
      chartType: 'horizontal-bar',
      data: [
        { stage: 'App Downloads', value: 100000 },
        { stage: 'Account Created', value: 72000 },
        { stage: 'KYC Complete', value: 54000 },
        { stage: 'First Send', value: 38000 },
        { stage: 'Repeat User', value: 24000 },
      ],
      xKey: 'stage',
      yKeys: ['value'],
      colors: ['#2BF2F1', '#60D06F', '#6060BF', '#F19D38', '#7BA882'],
    },
    notes: 'Funnel chart showing conversion from downloads (100K) to repeat users (24K). 24% conversion to repeat user.',
  },
  {
    type: 'chart',
    bg: 'dark',
    badge: 'Area Chart',
    title: 'Send Volume by Corridor',
    body: 'All corridors are growing — Mexico alone accounts for 45% of volume. Total send volume up 38% H1 2026.',
    chart: {
      chartType: 'area',
      data: [
        { month: 'Jan', mx: 3200, gt: 1800, sv: 1200, other: 900 },
        { month: 'Feb', mx: 3400, gt: 1900, sv: 1300, other: 1000 },
        { month: 'Mar', mx: 3800, gt: 2100, sv: 1400, other: 1100 },
        { month: 'Apr', mx: 4100, gt: 2300, sv: 1500, other: 1200 },
        { month: 'May', mx: 4500, gt: 2500, sv: 1700, other: 1300 },
        { month: 'Jun', mx: 4800, gt: 2700, sv: 1800, other: 1400 },
      ],
      xKey: 'month',
      yKeys: ['mx', 'gt', 'sv', 'other'],
      colors: ['#2BF2F1', '#60D06F', '#6060BF', '#F19D38'],
    },
    notes: 'Stacked area chart showing corridor volume Jan-Jun. 10.7K June total.',
  },
  {
    type: 'chart',
    bg: 'light',
    badge: 'Bullet Graph',
    title: 'KPI Performance vs Targets',
    body: 'CSAT exceeds target — NPS and first-send speed need focus. 3/5 targets met.',
    chart: {
      chartType: 'horizontal-bar',
      data: [
        { name: 'NPS Score', actual: 72 },
        { name: 'CSAT', actual: 88 },
        { name: 'First Send <5min', actual: 64 },
        { name: 'App Rating', actual: 92 },
        { name: 'Repeat Rate', actual: 68 },
      ],
      xKey: 'name',
      yKeys: ['actual'],
      colors: ['#2BF2F1'],
    },
    notes: 'Bullet graph showing 5 KPIs with horizontal progress bars, actual values, and target markers. Original has green/red coloring based on target attainment.',
  },
  {
    type: 'chart',
    bg: 'dark',
    badge: 'Choropleth',
    title: 'Send-to Markets',
    body: 'Mexico dominates with $2.1B in annual remittance volume. 7 active corridors, 3 new planned for Q4.',
    chart: {
      chartType: 'horizontal-bar',
      data: [
        { country: 'Mexico', volume: 2100 },
        { country: 'Guatemala', volume: 480 },
        { country: 'Colombia', volume: 380 },
        { country: 'El Salvador', volume: 320 },
        { country: 'Dom. Rep.', volume: 290 },
        { country: 'Honduras', volume: 260 },
        { country: 'Nicaragua', volume: 120 },
      ],
      xKey: 'country',
      yKeys: ['volume'],
      colors: ['#2BF2F1'],
    },
    notes: 'Geographic choropleth map showing send-to markets. Original renders as SVG map of Latin America with color intensity by volume.',
  },
  {
    type: 'chart',
    bg: 'light',
    badge: 'Sunburst',
    title: 'User Segmentation',
    body: 'Inner ring = active vs dormant, middle = behavior, outer = corridor. Repeat senders make up 45% of the active base.',
    chart: {
      chartType: 'donut',
      data: [
        { name: 'Active', value: 70 },
        { name: 'Dormant', value: 30 },
      ],
      xKey: 'name',
      yKeys: ['value'],
      colors: ['#2BF2F1', '#CFCABF'],
    },
    notes: 'Sunburst chart with three concentric rings. 70% active users. Original renders as nested rings with corridor breakdowns.',
  },
  {
    type: 'chart',
    bg: 'dark',
    badge: 'Parallel Coordinates',
    title: 'User Behavior Profiles',
    body: 'Power users score high across all axes — new users have high NPS potential. Power users represent 18% of base but 52% of volume.',
    chart: {
      chartType: 'radar',
      data: [
        { metric: 'Frequency', power: 95, occasional: 30, new: 15 },
        { metric: 'Amount', power: 70, occasional: 55, new: 40 },
        { metric: 'Tenure', power: 85, occasional: 60, new: 10 },
        { metric: 'Products', power: 90, occasional: 25, new: 15 },
        { metric: 'NPS', power: 88, occasional: 72, new: 65 },
      ],
      xKey: 'metric',
      yKeys: ['power', 'occasional', 'new'],
      colors: ['#2BF2F1', '#F19D38', '#6060BF'],
    },
    notes: 'Parallel coordinates chart with 5 vertical axes and 3 profile lines (Power User, Occasional, New User). 3 user segments.',
  },
  {
    type: 'chart',
    bg: 'light',
    badge: 'Word Cloud',
    title: 'Customer Feedback Themes',
    body: "'Fast', 'Easy', and 'Trusted' are the top three themes from 14K user reviews. Speed-related keywords appear in 47% of 5-star reviews.",
    chart: {
      chartType: 'horizontal-bar',
      data: [
        { word: 'Fast', count: 48 },
        { word: 'Easy', count: 44 },
        { word: 'Trusted', count: 40 },
        { word: 'Home', count: 38 },
        { word: 'Reliable', count: 36 },
        { word: 'Family', count: 34 },
        { word: 'Secure', count: 32 },
        { word: 'Simple', count: 30 },
        { word: 'Affordable', count: 28 },
        { word: 'Instant', count: 28 },
      ],
      xKey: 'word',
      yKeys: ['count'],
      colors: ['#2BF2F1'],
    },
    notes: 'Word cloud with 14 words in varying sizes and colors. Original renders as scattered text with size proportional to frequency.',
  },
  {
    type: 'chart',
    bg: 'dark',
    badge: 'Chord Diagram',
    title: 'Money Flow Corridors',
    body: 'All flows originate from USA. USA-to-Mexico corridor carries 55% of total flow. $3.8B annual volume.',
    chart: {
      chartType: 'donut',
      data: [
        { name: 'MX', value: 55 },
        { name: 'GT', value: 15 },
        { name: 'SV', value: 10 },
        { name: 'HN', value: 10 },
        { name: 'CO', value: 10 },
      ],
      xKey: 'name',
      yKeys: ['value'],
      colors: ['#2BF2F1', '#60D06F', '#6060BF', '#F19D38', '#7BA882'],
    },
    notes: 'Chord diagram showing money flows from USA to 5 destination countries. Original renders as SVG arcs with bezier curves.',
  },
  {
    type: 'chart',
    bg: 'light',
    badge: 'Candlestick',
    title: 'MXN/USD Exchange Rate',
    body: 'Trend is favorable for senders this week. FX spread locked at 0.5% — best in class for digital.',
    chart: {
      chartType: 'bar',
      data: [
        { day: 'Mon', close: 17.5 },
        { day: 'Tue', close: 17.3 },
        { day: 'Wed', close: 17.8 },
        { day: 'Thu', close: 17.6 },
        { day: 'Fri', close: 18.1 },
        { day: 'Mon2', close: 17.9 },
        { day: 'Tue2', close: 18.4 },
        { day: 'Wed2', close: 18.2 },
      ],
      xKey: 'day',
      yKeys: ['close'],
      colors: ['#60D06F'],
    },
    notes: 'Candlestick chart showing MXN/USD exchange rate over 8 trading days. Original has green/red candles with wicks. 18.4 latest rate.',
  },
  {
    type: 'chart',
    bg: 'dark',
    badge: 'Violin Plot',
    title: 'Fee Distribution by Corridor',
    body: 'Mexico has the tightest fee distribution — Guatemala shows the most variance. Flat fee model preferred 3:1 over percentage-based.',
    chart: {
      chartType: 'bar',
      data: [
        { corridor: 'MX', median: 3.5 },
        { corridor: 'GT', median: 4.2 },
        { corridor: 'SV', median: 3.8 },
        { corridor: 'CO', median: 4.0 },
      ],
      xKey: 'corridor',
      yKeys: ['median'],
      colors: ['#2BF2F1', '#60D06F', '#6060BF', '#F19D38'],
    },
    notes: 'Violin plot for 4 corridors. Original renders as mirrored density curves with quartile boxes. $3.50 MX median fee.',
  },
  {
    type: 'chart',
    bg: 'light',
    badge: 'Pictorial Chart',
    title: 'User Journey Milestones',
    body: 'Each dot = 1% of users. Only 12% adopt multiple products — our growth opportunity. Multi-product users have 3x higher LTV.',
    chart: {
      chartType: 'horizontal-bar',
      data: [
        { milestone: 'Signed Up', pct: 100 },
        { milestone: 'Verified', pct: 72 },
        { milestone: 'First Send', pct: 38 },
        { milestone: 'Repeat', pct: 24 },
        { milestone: 'Multi-Product', pct: 12 },
      ],
      xKey: 'milestone',
      yKeys: ['pct'],
      colors: ['#2BF2F1'],
    },
    notes: 'Pictorial chart with 5 milestone rows. Original uses segmented dot grids (20 segments each). 12% reach multi-product.',
  },
  {
    type: 'chart',
    bg: 'dark',
    badge: 'Gauge Chart',
    title: 'Net Promoter Score',
    body: "Félix NPS sits firmly in 'Excellent' territory, up 8 points from last quarter. Promoters cite speed and transparency most often.",
    chart: {
      chartType: 'donut',
      data: [
        { name: 'NPS', value: 72 },
        { name: 'Remaining', value: 28 },
      ],
      xKey: 'name',
      yKeys: ['value'],
      colors: ['#2BF2F1', '#082422'],
    },
    notes: "Gauge chart with semicircular arc. Needle points to 72/100 'Excellent'. Original renders as custom SVG gauge with colored segments.",
  },
]

async function main() {
  const user = await getUserByEmail('kyle.cooney@felixpago.com')
  if (!user) {
    console.error('User kyle.cooney@felixpago.com not found in studio DB')
    process.exit(1)
  }

  console.log(`Found user: ${user.name} (${user.id})`)

  const pres = await createPresentation(
    user.id,
    'Team Weekly',
    'Team weekly presentation template with company north star, values, meeting rules, OKRs, org chart, product demo, and a comprehensive data visualization showcase (28+ chart types)',
    slides,
    'anthropic',
    'claude-sonnet-4-20250514',
    {
      title: 'Team Weekly — Félix Pago',
      type: 'general',
      summary: 'A comprehensive team weekly template covering company mission, values, meeting rules, agenda, OKR tracking, product demo, org chart, and an extensive data visualization showcase featuring bar charts, line charts, donut charts, scatter plots, radar charts, funnels, area charts, and many more.',
      sections: [
        { title: 'North Star & Values', content: 'Company mission, key principles, and the six Félix values that guide every decision.', slideIndex: 0 },
        { title: 'Meeting Framework', content: 'Rules of engagement for team weeklies: share what matters, be concise, limit demos, follow the OAI structure.', slideIndex: 2 },
        { title: 'Weekly Agenda & OKRs', content: 'Agenda items with time allocations and OKR tracking with status indicators.', slideIndex: 3 },
        { title: 'Product & Team', content: 'Product demo walkthrough and organizational chart.', slideIndex: 5 },
        { title: 'Data Visualization Showcase', content: 'Comprehensive showcase of 28+ chart types including bar, stacked bar, horizontal bar, line, multi-line, donut, scatter, histogram, heat map, treemap, sankey, waterfall, box plot, bubble, radar, gantt, funnel, area, bullet graph, choropleth, sunburst, parallel coordinates, word cloud, chord, candlestick, violin, pictorial, and gauge charts.', slideIndex: 7 },
      ],
    },
  )

  console.log(`Created presentation: ${pres.id}`)
  console.log(`Title: ${pres.title}`)
  console.log(`Slides: ${pres.slides.length}`)
  console.log(`Done! View at /create/${pres.id}`)
}

main().catch(console.error)
